
platform :ios, '8.0'

source 'git@gitlab.corp.tujia.com:AnBaniOS/ABPrivateSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'ABSDKDemo' do
    use_frameworks!
#    pod 'ABAuthKit'
    pod 'AFNetworking','~>3.0'
end

